version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - library-network
  library-api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/fastapi-library
    networks:
      - library-network
    
networks:
  library-network:
    name: library-network
    driver: bridge
