"""Add is_active to Books and Authors

Revision ID: fe811b7f17d9
Revises: 66a3de137daa
Create Date: 2023-06-21 15:05:49.641606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe811b7f17d9'
down_revision = '66a3de137daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_active')
    op.drop_column('authors', 'is_active')
    # ### end Alembic commands ###
